### ISSUE TITLE
Train & Test CSV already available

### ISSUE THREAD

**Issue by Prashambhuta** [Prashambhuta/stats_and_ds_applications#1]
## Introduction
Training and testing CSV is already provided by the booking.com. You can access them in then booking-challenge directory.

**Mark this issue closed when you read it and if everything is OK.**

PS. Welcome to *Issues*, here you can communicate, assign tasks, report bugs with team members. :)

**Comment by Prashambhuta** [comment]
Close this issue?

**Comment by AdrianFischerBCN** [comment]
Ok
